export const TAURI_COMMANDS = {
	DATABASE_INITIALIZE: 'database_initialize',
	DATABASE_CHECK_HEALTH: 'database_check_health',
	DATABASE_READ_SCHEMA_VERSION: 'database_read_schema_version',
	DOCUMENTS_CREATE: 'documents_create',
	DOCUMENTS_GET_BY_ID: 'documents_get_by_id',
	DOCUMENTS_LIST: 'documents_list',
	DOCUMENTS_LIST_RECENT: 'documents_list_recent',
	DOCUMENTS_LIST_TRASHED: 'documents_list_trashed',
	DOCUMENTS_OPEN: 'documents_open',
	DOCUMENTS_OPEN_SCENE: 'documents_open_scene',
	DOCUMENTS_RENAME: 'documents_rename',
	DOCUMENTS_MOVE_TO_TRASH: 'documents_move_to_trash',
	DOCUMENTS_RESTORE: 'documents_restore',
	FILES_PREPARE_LOCAL_DIRECTORIES: 'files_prepare_local_directories',
	FILES_READ_LOCAL_DIRECTORIES: 'files_read_local_directories',
	FILES_RESOLVE_DATA_DIR: 'files_resolve_data_dir',
	FILES_RESOLVE_CONFIG_DIR: 'files_resolve_config_dir',
	FILES_RESOLVE_DOCUMENT_LAYOUT: 'files_resolve_document_layout',
	SETTINGS_READ: 'settings_read',
	SETTINGS_SAVE: 'settings_save',
	EDITOR_SAVE_SCENE: 'editor_save_scene',
	SYSTEM_DEMO: 'system_demo',
} as const
