export { default as ActivityBar } from './ActivityBar'
export { default as RightPanel } from './RightPanel'
export { default as StatusBar } from './StatusBar'
export { default as WorkbenchTabs } from './WorkbenchTabs'
export { default as WorkbenchTitleBar } from './WorkbenchTitleBar'
export { WorkbenchShellProvider, useWorkbenchShell } from './WorkbenchShellBridge'
export type { WorkbenchPanelKey, WorkbenchShellState } from './WorkbenchShellBridge'
