export { default as ActivityBar } from './ActivityBar'
export { default as CanvasShell } from './CanvasShell'
export { default as RightPanel } from './RightPanel'
export { default as StatusBar } from './StatusBar'
export { default as WorkbenchMetaRail } from './WorkbenchMetaRail'
export { default as WorkbenchResizableShell } from './WorkbenchResizableShell'
export { default as WorkbenchShellFrame } from './WorkbenchShellFrame'
export { default as WorkbenchSidePanel } from './WorkbenchSidePanel'
export { default as WorkbenchTabs } from './WorkbenchTabs'
export { default as WorkbenchTitleBar } from './WorkbenchTitleBar'
export { resolveSaveStatusMeta } from './save-status'
export { WorkbenchShellProvider, useWorkbenchShell, useWorkbenchShellController } from './WorkbenchShellBridge'
export type { WorkbenchShellState } from './WorkbenchShellBridge'
